version: "3.10"
services:
  web:
    build:
       context: .
       dockerfile: Dockerfile
    image: python-flask-redis
    ports:
      - "5000:5000"
    volumes:
      - .:/root/composetest
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
